---
title: "Kerui Notebook"
author: "Kerui Yang"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: true
    code_folding: hide
    self_contained: yes
    theme: spacelab
---

```{r setup, include=FALSE, eval=TRUE}
knitr::opts_chunk$set(cache = TRUE, message = FALSE, warning = FALSE, fig.height = 7, fig.width = 9)

```

```{r libraries}
library(tidyverse)
library(SingleCellExperiment)
library(Statial)
#library(spicyR)
library(plotly)
library(ClassifyR)
library(lisaClust)
library(ggsurvfit)
library(ggthemes)
library(DT)
library(htmlwidgets)
library(ggthemes)

# Set ggplot theme
theme_set(theme_classic())

```

## Loading in datasets


```{r data}
load("./data/kerenSCE.rda")
load("./data/aliSCE.rda")

aliSCE 
```


```{r}
set.seed(51773)
aliSCE <- scater::runUMAP(aliSCE, exprs_values = "intensities", name = "UMAP")

scater::plotReducedDim(aliSCE, dimred = "UMAP", colour_by = "cellType")
```
```{r}
p = aliSCE |> 
  colData() |> 
  data.frame() |>
  filter(image_number == "527") |> 
  ggplot(aes(x = x, y = y, col = cellType)) +
  geom_point(size = 1) +
  ggthemes::scale_colour_tableau( palette = "Tableau 20")


ggplotly(p)
```


```{r}
p1 = aliSCE |> 
  colData() |> 
  data.frame() |>
  filter(image_number == "345") |> 
  ggplot(aes(x = x, y = y, col = cellType)) +
  geom_point(size = 1) +
  ggthemes::scale_colour_tableau( palette = "Tableau 20")


ggplotly(p1)

```

```{r}
p2 = aliSCE |> 
  colData() |> 
  data.frame() |>
  filter(image_number =) |> 
  ggplot(aes(x = x, y = y, col = cellType)) +
  geom_point(size = 1) +
  ggthemes::scale_colour_tableau( palette = "Tableau 20")


ggplotly(p2)
```


##Converting into dataframe
```{r}

# p3 = aliSCE |> 
#   colData() |> 
#   data.frame() 
# 
# p3
# 
# write.csv(p3, "aliSCE1.csv", row.names=FALSE)
```
```{r}

##lr >0(relapse)
names(p3)
filtered_p4 = filter(p3, complete_rec_history == "YES")
```
```{r}
dplyr::count(filtered_p4, lr, sort = TRUE)
```
```{r}
p3 = aliSCE |> 
  colData() |> 
  data.frame() 
filtered_p4 = filter(p3, complete_rec_history == "YES")

lr_0 <- unique(filtered_p4[filtered_p4$lr == 0, "image_number"])
lr_1 <- unique(filtered_p4[filtered_p4$lr == 1, "image_number"])
lr_0
lr_1
```   
```{r}
regionMap(aliSCE,
          cellType = "cellType")
```


```{r}

p = hatchingPlot(
  aliSCE,
  useImages = "527",
  cellType = "cellType",
  spatialCoords = c("x", "y"),
  line.spacing = 41, # spacing of lines
  nbp = 100 # smoothness of lines
)

p +
  ggthemes::scale_colour_tableau( palette = "Tableau 20") +
  guides(fill=guide_legend(ncol=2))

```

